apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: YOUR_DOCKERHUB_USERNAME/todo-backend
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: task-db
          mountPath: /app
      volumes:
      - name: task-db
        persistentVolumeClaim:
          claimName: backend-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  selector:
    app: todo-backend
  ports:
  - port: 5000
    targetPort: 5000
  clusterIP: ClusterIP